export const initialTestPageTextEn = {
  title: "Initial test",
  seeCoursesButtonText: "See courses",
  startButtonText: "Start the initial test",
  nextButtonText: "Next question",
  endButtonText: "Submit initial test",
  paragraph1: `The initial test consists of 50
  questions, and you have to answer each one. Only one of the offered answers is correct.`,
  paragraph2: `Your score on this test will help us determine which courses are most suitable for you.`,
  completedParagraph: `You have already completed the initial
  test.`,
  questions: [
    {
      title: "What do you say when you meet someone?",
      answers: [
        "Can I have some coffee, please?",
        "Hello! My name is (your name).",
        "How much is this?",
        "Move away!",
        "I’m leaving tomorrow afternoon.",
      ],
      correctAnswer: "Hello! My name is (your name).",
      forCourse: 3,
    },
    {
      title: "Which are the family members?",
      answers: [
        "Train, plain, bus",
        "Orange, apple, banana",
        "Mom, dad, sister",
        "Arm, leg, head",
        "Monday, Wednesday, Friday",
      ],
      correctAnswer: "Mom, dad, sister",
      forCourse: 3,
    },
    {
      title: "Which answer tells the time?",
      answers: [
        "It's one o'clock.",
        "It's €3.50.",
        "It's 7th October.",
        "It was a good game.",
        "It happened a long time ago.",
      ],
      correctAnswer: "It's one o'clock.",
      forCourse: 3,
    },
    {
      title: "How do we read $5.90?",
      answers: [
        "Five dollars nineteen cents.",
        "Five euros ninety.",
        "It’s almost six o’clock.",
        "Five dollars bill.",
        "Five dollars ninety.",
      ],
      correctAnswer: "Five dollars ninety.",
      forCourse: 3,
    },
    {
      title: "Circle body parts on the face.",
      answers: [
        "Legs, knee",
        "Arms, fingers",
        "Hair, neck",
        "Eyes, mouth",
        "Back, stomach",
      ],
      correctAnswer: "Eyes, mouth",
      forCourse: 3,
    },
    {
      title: "Which one is an e-mail address:",
      answers: [
        "Name and Surname",
        "Monkey Street #37",
        "Money_tree@gmail.com",
        "Home sweet home",
        "Digital Education for all",
      ],
      correctAnswer: "Money_tree@gmail.com",
      forCourse: 4,
    },
    {
      title:
        "Which field do you have to fill with email so recipients don't see who the mail was sent to?",
      answers: [
        "TO field",
        "CC field",
        "BCC field",
        "All of the above",
        "None of the above",
      ],
      correctAnswer: "BCC field",
      forCourse: 4,
    },
    {
      title: "In which email folder can you find unwanted emails?",
      answers: ["Inbox", "Sent items", "Spam", "Outbox", "Drafts"],
      correctAnswer: "Spam",
      forCourse: 4,
    },
    {
      title: "Where can a person check his or her emails?",
      answers: [
        "On a personal computer",
        "On a cell phone",
        "On a tablet",
        "All of the above",
      ],
      correctAnswer: "All of the above",
      forCourse: 4,
    },
    {
      title: "Which is the shortcut for copying content in Microsoft Word?",
      answers: ["Ctrl + X", "Ctrl + C", "Ctrl + V", "Ctrl + P"],
      correctAnswer: "Ctrl + C",
      forCourse: 4,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 1,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 1,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 1,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 1,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 1,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 2,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 2,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 2,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 2,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 2,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 5,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 5,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 5,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 5,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 5,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 6,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 6,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 6,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 6,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 6,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 7,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 7,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 7,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 7,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 7,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 8,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 8,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 8,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor. 1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 8,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor 2.",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 8,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 9,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 9,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 9,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 9,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 9,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.2",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 10,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
        "Dummy netočan odgovor.1",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 10,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor.1",
        "Dummy netočan odgovor.2",
        "Dummy netočan odgovor.3",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 10,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor. 1",
        "Dummy točan odgovor. ",
        "Dummy netočan odgovor. 2",
        "Dummy netočan odgovor. 3",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 10,
    },
    {
      title: "Dummy pitanje?",
      answers: [
        "Dummy netočan odgovor. 2",
        "Dummy netočan odgovor. 3",
        "Dummy netočan odgovor. 1",
        "Dummy točan odgovor.",
      ],
      correctAnswer: "Dummy točan odgovor.",
      forCourse: 10,
    },
  ],
};
