export function RIASECTypeEn(letter: string) {
  if (letter == "R") {
    return {
      title: "Realistic (Doers)",
      characteristics: `Realistic individuals are active and stable and enjoy hands-on or manual activities, such as building, mechanics, machinery operation and athletics. They prefer to work with things rather than ideas and people. They enjoy engaging in physical activity and often like being outdoors and working with plants and animals. People who fall into this category generally prefer to “learn by doing” in a practical, task-oriented setting, as opposed to spending extended periods of time in a classroom. Realistic types tend to communicate in a frank, direct manner and value material things. They perceive themselves as skilled in mechanical and physical activities but may be uncomfortable or less adept with human relations. The preferred work environment of the realistic type fosters technical competencies and work that allows them to produce tangible results. Typical realistic careers include electrician, engineer, veterinarian and the military.`,
      personalCharacteristics: [
        "Practical",
        "Aathletic",
        "Straightforward",
        "Mechanically inclined",
        "A nature lover",
        "Curious about the physical world",
      ],
      activities: [
        "Fix electrical things",
        "Solve mechanical problems",
        "Pitch a tent",
        "Play a sport",
        "Read a blueprint",
        "Operate tools and machinery",
      ],
      jobs: [
        "Aerospace/Aeronautical Engineer (with Investigative)",
        "Agriculture",
        "Animals",
        "Anthropology/Paleontology (with Investigative)",
        "Architect (with Artistic and Enterprising)",
        "Astronomy (with Investigative)",
        "Athletics",
        "Carpenter (with Conventional and Investigative)",
        "Culinary arts (with Artistic and Enterprising)",
        "Chemistry/Chemist (with Investigative and Conventional)",
        "Computer engineering/Computer science/Information technology/Computer programmer (with Investigative and Conventional)",
        "Dance (with Artistic)",
        "Dentist (with Investigative and Social)",
        "Engineer (with Investigative and Conventional)",
        "Environmental science",
        "Fashion design (with Artistic and Enterprising)",
        "Fine Artist, Including Painter, Sculptor and Illustrator (with Artistic)",
        "Firefighter (with Social and Enterprising)",
        "Graphic designer (with Artistic and Enterprising)",
        "Interior design (with Artistic)",
        "Model (people) (with Artistic and Enterprising)",
        "Musician (with Artistic and Enterprising)",
        "Nurse (with Social, Conventional, and Investigative)",
        "Outdoor recreation",
        "Park Naturalist (with Social and Artistic)",
        "Personal trainer (with Enterprising and Social)",
        "Photographer (with Artistic and Enterprising)",
        "Physical therapy (with Social and Investigative)",
        "Driver",
        "Surgeon (with Investigative and Social)",
        "Veterinarian (with Investigative and Social)",
        "Web developer (with Conventional, Artistic, and Investigative)",
        "Zoologists and Wildlife Biologists (with Investigative)",
      ],
    };
  } else if (letter == "I") {
    return {
      title: "Investigative (Thinkers)",
      characteristics: `Investigative individuals are analytical, intellectual and observant and enjoy research, mathematical or scientific activities. They are drawn to ambiguous challenges and may be stifled in highly structured environments. People who fall into this category enjoy using logic and solving highly complex, abstract problems. Because they are introspective and focused on creative problem solving, investigative types often work autonomously and do not seek leadership roles. They place a high value on science and learning and perceive themselves as scholarly and having scientific or mathematical ability but lacking leadership and persuasive skills. The preferred work environment of the investigative type encourages scientific competencies, allows independent work and focuses on solving abstract, complex problems in original ways. Typical investigative careers include medical technologist, biologist, chemist and systems analyst.`,
      personalCharacteristics: [
        "Inquisitive",
        "Analytical",
        "Scientific",
        "Observant",
        "Logical",
        "Precise",
      ],
      activities: [
        "Think abstractly",
        "Solve math problems",
        "Understand physics theories",
        "Do complex calculations",
        "Use a microscope",
        "Interpret formulas",
      ],
      jobs: [
        "Actuary (with Conventional and Enterprising)",
        "Archivist/Librarian (with Social and Conventional)",
        "Biostatistics/Masters in Public Health (with Conventional)",
        "Carpenter (with Conventional and Realistic)",
        "Chemistry/Chemist (with Realistic and Conventional)",
        "Community Health Workers/Masters in Public Health (with Social and Enterprising)",
        "Computer engineering/Computer science/Information technology/Computer programmer (with Realistic and Conventional)",
        "Counselor (with Social and Artistic)",
        "Dentist (with Realistic and Social)",
        "Dietitian/Nutritionist (with Social and Enterprising)",
        "Economics (with Conventional and Social)",
        "Engineer (with Realistic and Conventional)",
        "Epidemiology/Masters in Public Health (with Social)",
        "Finance (with Enterprising and Conventional)",
        "Lawyer (with Enterprising and Social)",
        "Mathematician (with Artistic)",
        "Nurse (with Realistic, Conventional, and Social)",
        "Pharmacist (with Social and Conventional)",
        "Physical therapy (with Social and Realistic)",
        "Physician (Medical school/Medical research) (with Social)",
        "Physics",
        "Poets, Lyricists and Creative Writers (with Artistic)",
        "Professor/Research – Ph.D.",
        "Psychology/Psychologist (with Social and Artistic)",
        "Social Work",
        "Surgeon (with Realistic and Social)",
        "Technical writer (with Artistic and Conventional)",
        "Tutor (with Social)",
        "Veterinarian (with Realistic and Social)",
        "Web developer (with Conventional, Realistic, and Artistic)",
        "Zoologists and Wildlife Biologists(with Realistic)",
      ],
    };
  } else if (letter == "A") {
    return {
      title: "Artistic (Creators)",
      characteristics: `Artistic individuals are original, intuitive and imaginative and enjoy creative activities, such as composing or playing music, writing, drawing or painting and acting in or directing stage productions. They seek opportunities for self-expression through artistic creation. People who fall into this category prefer flexibility and ambiguity and have an aversion to convention and conformity. Artistic types are generally impulsive and emotional and tend to communicate in a very expressive and open manner. They value aesthetics and view themselves as creative, non-conforming and as appreciating or possessing musical, dramatic, artistic or writing abilities while lacking clerical or organizational skills. The preferred work environment of the artistic type fosters creative competencies, and encourages originality and use of the imagination in a flexible, unstructured setting. Typical artistic careers include musician, reporter and interior decorator.`,
      personalCharacteristics: [
        "Creative",
        "Intuitive",
        "Imaginative",
        "Innovative",
        "Sensitive",
        "An individualist",
      ],
      activities: [
        "Sketch, draw, paint",
        "Use intuition",
        "Play a musical instrument",
        "Write stories, poetry, music",
        "Develop new ideas, approaches",
        "Design fashions or interiors",
      ],
      jobs: [
        "Architect (with Realistic and Enterprising)",
        "Broadcast journalism (with Enterprising)",
        "Clergy (with Social and Enterprising)",
        "Counselor (with Investigative and Social)",
        "Culinary arts (with Realistic and Enterprising)",
        "Dance (with Realistic)",
        "Fashion design (with Realistic and Enterprising)",
        "Fine Artist, Including Painter, Sculptor and Illustrator (with Realistic)",
        "Graphic designer (with Enterprising and Realistic)",
        "Interior design (with Realistic)",
        "Model (people) (with Realistic and Enterprising)",
        "Musician (with Enterprising and Realistic)",
        "Park Naturalist (with Social and Realistic)",
        "Poets, Lyricists and Creative Writers (with Investigative)",
        "Psychology/Psychologist (with Social and Investigative); Art therapist/Dance therapy/Drama therapy/Music therapy (with social)",
        "Public relations (with Enterprising)",
        "Photographer (with Realistic and Enterprising)",
        "Teacher (with Social)",
        "Technical writer (with Investigative and Conventional)",
        "Trainer (business) (with Social and Conventional)",
        "Web developer (with Conventional, Realistic, and Investigative)",
      ],
    };
  } else if (letter == "S") {
    return {
      title: "Social (Helpers)",
      characteristics: `Social individuals are humanistic, idealistic, responsible and concerned with the welfare of others. They enjoy participating in group activities and helping, training, healing, counseling or developing others. They are generally focused on human relationships and enjoy social activities and solving interpersonal problems. Social types seek opportunities to work as part of a team, solve problems through discussions and utilize interpersonal skills but may avoid activities that involve systematic use of equipment or machines. Because they genuinely enjoy working with people, they communicate in a warm and tactful manner and can be persuasive. They view themselves as understanding, helpful, cheerful and skilled in teaching but lacking in mechanical ability. The preferred work environment of the social type encourages teamwork and allows for significant interaction with others. Typical social careers include teacher, counselor and social worker.`,
      personalCharacteristics: [
        "Friendly",
        "Helpful",
        "Idealistic",
        "Insightful about people",
        "Outgoing with others",
        "Understanding",
      ],
      activities: [
        "Teach or train others",
        "Express your feelings clearly",
        "Lead a group discussion",
        "Mediate disputes",
        "Cooperate well with others",
        "Work well in groups or teams",
      ],
      jobs: [
        "Archivist/Librarian (with Conventional and Investigative)",
        "Clergy (with Artistic and Enterprising)",
        "Community Organizer",
        "Community Health Workers/Masters in Public Health (with Investigative and Enterprising)",
        "Counselor (with Investigative and Artistic)",
        "Customer service (with Conventional and Enterprising)",
        "Dentist (with Investigative and Realistic)",
        "Dietitian/Nutritionist (with Investigative and Enterprising)",
        "Economics (with Investigative and Conventional)",
        "Education (Teacher/Counselor/Administration)",
        "Educational administration (with Enterprising and Conventional)",
        "Epidemiology/Masters in Public Health (with Investigative)",
        "Firefighter (with Realistic and Enterprising)",
        "Fitness Trainer and Aerobics Teacher (with Enterprising and Realistic)",
        "Foreign Service/Diplomacy (with Enterprising and Artistic)",
        "Human Resources (with Conventional and Enterprising)",
        "Lawyer (with Investigative and Enterprising)",
        "Nurse (with Realistic, Conventional, and Investigative)",
        "Park Naturalist (with Realistic and Artistic)",
        "Pharmacist (with Investigative and Conventional)",
        "Physical therapy (with Realistic and Investigative)",
        "Physician (Medical school/Medical research) (with Investigative)",
        "Psychology/Psychologist (with Investigative and Artistic)",
        "Public Health Educator/Masters in Public Health (with Enterprising)",
        "Religion",
        "Social Advocate",
        "Sociology",
        "Social Work",
        "Surgeon (with Realistic and Investigative)",
        "Teacher (Early childhood education, Primary school, Secondary school, Teaching English as a second language, Special Ed, and Substitute teaching) (with Artistic)",
        "Trainer (business) (with Artistic and Conventional)",
        "Tutor (with Investigative)",
        "Veterinarian (with Investigative and Realistic)",
      ],
    };
  } else if (letter == "E") {
    return {
      title: "Enterprising (Persuaders)",
      characteristics: `Enterprising individuals are energetic, ambitious, adventurous, sociable and self-confident. They enjoy activities that require them to persuade others, such as sales, and seek out leadership roles. They are invigorated by using their interpersonal, leadership and persuasive abilities to obtain organizational goals or economic gain but may avoid routine or systematic activities. They are often effective public speakers and are generally sociable but may be viewed as domineering. They view themselves as assertive, self-confident and skilled in leadership and speaking but lacking in scientific abilities. The preferred work environment of the enterprising type encourages them to engage in activities, such as leadership, management and selling, and rewards them through the attainment of money, power and status. Typical enterprising careers include salesperson, business executive and manager.`,
      personalCharacteristics: [
        "Self-confident",
        "Assertive",
        "Sociable",
        "Persuasive",
        "Enthusiastic",
        "Energetic",
      ],
      activities: [
        "Initiate projects",
        "Convince people to do things your way",
        "Sell things or promote ideas",
        "Give talks or speeches",
        "Organize activities and events",
        "Lead a group",
      ],
      jobs: [
        "Actuary (with Investigative and Conventional)",
        "Architect (with Artistic and Realistic)",
        "Buyer",
        "Community Health Workers/Masters in Public Health (with Investigative and Social)",
        "Culinary arts (with Artistic and Realistic)",
        "Clergy (with Artistic and Social)",
        "Customer service (with Conventional and Social)",
        "Dietitian/Nutritionist (with Social and Investigative)",
        "Educational administration (with Social and Conventional)",
        "Entrepreneur and Business",
        "Fashion design (with Artistic and Realistic)",
        "Finance (with Conventional and Investigative)",
        "Foreign Service/Diplomacy (with Social and Artistic)",
        "Firefighter (with Social and Realistic)",
        "Fitness Trainer and Aerobics Teacher (with Realistic and Social)",
        "Fundraising",
        "Graphic designer (with Artistic and Realistic)",
        "Human Resources (with Conventional and Social)",
        "Broadcast journalism (with Artistic)",
        "Lawyer (with Investigative and Social)",
        "Management/Management Consultant",
        "Market Research Analyst (with Investigative)",
        "Model (people) (with Artistic and Realistic)",
        "Musician (with Artistic and Realistic)",
        "Photographer (with Artistic and Realistic)",
        "Politics",
        "Public Health Educator/Masters in Public Health (with Social)",
        "Public relations/Publicity/Advertising/Marketing (with Artistic)",
        "Public speaking",
        "Real Estate Agent (with Conventional)",
        "Sales (with Conventional and Social)",
      ],
    };
  } else if (letter == "C") {
    return {
      title: "Conventional (Organizers)",
      characteristics: `Conventional individuals are efficient, careful, conforming, organized and conscientious. They are comfortable working within an established chain of command and prefer carrying out well-defined instructions over assuming leadership roles. They prefer organized, systematic activities and have an aversion to ambiguity. They are skilled in and often enjoy maintaining and manipulating data, organizing schedules and operating office equipment. While they rarely seek leadership or “spotlight” roles, they are thorough, persistent and reliable in carrying out tasks. Conventional types view themselves as responsible, orderly and efficient, and possessing clerical, organizational and numerical abilities. They may also see themselves as unimaginative or lacking in creativity. The preferred work environment of the conventional type fosters organizational competencies, such as record keeping and data management, in a structured operation and places high value on conformity and dependability. Typical conventional careers include secretary, accountant and banker.`,
      personalCharacteristics: [
        "Well-organized",
        "Accurate with details and numbers",
        "Interested in number crunching",
        "Methodical",
        "Conscientious about facts",
        "Efficient",
      ],
      activities: [
        "Work well within an authority system or organization",
        "Write reports",
        "Keep accurate records",
        "Use a computer terminal",
        "Perform calculations",
        "Gather, organize and report data",
      ],
      jobs: [
        "Accounting/Tax advisor (with Enterprising)",
        "Actuary (with Investigative and Enterprising)",
        "Archivist/Librarian (with Social and Investigative)",
        "Biostatistics/Masters in Public Health (with Investigative)",
        "Carpenter (with Realistic and Investigative)",
        "Chemistry/Chemist (with Investigative and Realistic)",
        "Computer engineering/Computer science/Information technology/Computer programmer (with Investigative and Realistic)",
        "Customer service (with Enterprising and Social)",
        "Economics (with Investigative and Social)",
        "Educational administration (with Social and Enterprising)",
        "Engineer (with Investigative and Realistic)",
        "Finance (with Enterprising and Investigative)",
        "Human Resources (with Enterprising and Social)",
        "Math teacher (with Social)",
        "Nurse (with Realistic, Social, and Investigative)",
        "Office administration (with Enterprising)",
        "Pharmacist (with Social and Investigative)",
        "Real Estate Agent (with Enterprising)",
        "Statistician (with Realistic and Investigative)",
        "Technical writer (with Artistic and Investigative)",
        "Trainer (business) (with Social and Artistic)",
        "Web developer (with Artistic, Realistic, and Investigative)",
      ],
    };
  }
}
